---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Mark Martinez.
--- DateTime: 2025-04-04 5:11 a.m.
---

function love.load()

end

function love.update(dt)

end

function love.draw()

end

function love.quit()

end